version: '2.3'
services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8088
    network_mode: host
    volumes:
      - /opt/docker_volume/qbittorrent_config:/config
      - /mnt/cifs/download:/downloads
      - /mnt/cifs/av:/av
      - /mnt/cifs/media/movies:/movies
      - /mnt/cifs/media/tv shows:/tv
    restart: always
