services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
    network_mode: host
    volumes:
      - config:/config
      - download:/downloads
      - av:/av
      - movies:/movies
      - tv:/tv
    dns:
      - 223.5.5.5
      - 114.114.114.114
    restart: always
    
volumes:
  config:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=172.28.28.29,rw,vers=4.0,soft,nolock"
      device: "	:/mnt/zpool0/docker_volume/qbittorrent_config"
  download:
    driver: local
    driver_opts:
      type: cifs
      o: "username=docker,password=docker"
      device: "	//172.28.28.29/download"
  av:
    driver: local
    driver_opts:
      type: cifs
      o: "username=docker,password=docker"
      device: "//172.28.28.29/av"
  movies:
    driver: local
    driver_opts:
      type: cifs
      o: "username=docker,password=docker"
      device: "//172.28.28.29/multimedia/Movies"
  tv:
    driver: local
    driver_opts:
      type: cifs
      o: "username=docker,password=docker"
      device: "//172.28.28.29/multimedia/TV Shows"
