version: "2.1"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    stdin_open: true
    tty: true
    networks:
      static_ip:
        ipv4_address: 172.28.28.44
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - /opt/docker_volume/heimdall_config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
networks:
  static_ip:
    external: true
