version: "2.3"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    stdin_open: true
    tty: true
    network_mode: "host"
    restart: "always"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PUID=0
      - PGID=0
      - VERSION=docker
      - TZ=Asia/Shanghai
    volumes:
      - /opt/docker_volume/plex_config:/config
      - /root/docker_volume/cifs/media:/data
      - /dev/shm:/transcode
