version: "2.1"
services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbcmcc
    stdin_open: true
    tty: true
    network_mode: host
    restart: always
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent_config:/config
      - /mnt/download:/downloads
      - /mnt/av:/av
      - /mnt/media:/media
