version: "2.3"
services:
  plex:
    image: emby/embyserver
    container_name: emby
    stdin_open: true
    tty: true
    network_mode: host
    restart: unless-stopped
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - UID=0
      - GID=0
      - GIDLIST=44,108
      - TZ=Asia/Shanghai
    volumes:
      - /opt/docker_volume/emby_config:/config
      - /root/docker_volume/cifs/av:/av
      - /root/docker_volume/cifs/media:/data
      - /dev/shm:/transcode
