version: "2.3"
services:
  emby:
    image: emby/embyserver:latest
    container_name: emby
    network_mode: "host"
    restart: unless-stopped
    runtime: nvidia
    environment:
      - UID=0
      - GID=0
      - GIDLIST=44,108
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /opt/docker_volume/emby_config:/config
      - /dev/shm:/mnt/transcode
      - /root/docker_volume/cifs/media:/mnt/media
      - /root/docker_volume/cifs/av:/mnt/av
