version: "2.3"
services:
  plex:
    image: emby/embyserver
    container_name: emby
    stdin_open: true
    tty: true
    restart: unless-stopped
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - UID=0
      - GID=0
      - GIDLIST=44,108
      - TZ=Asia/Shanghai
    ports:
      - 8096:8096
      - 8920:8920
    volumes:
      - /opt/docker_volume/emby_config:/config
      - /mnt/cifs/cifs/av:/av
      - /mnt/cifs/cifs/media:/data
      - /dev/shm:/transcode
