version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    stdin_open: true
    tty: true
    networks:
      static_ip:
        ipv4_address: 172.28.28.33
    environment:
      TZ: Asia/Shanghai
      PIHOLE_DNS_: 223.5.5.5;114.114.114.114
      SKIPGRAVITYONBOOT: 1
    volumes:
      - /opt/docker_volume/pihole/etc-pihole:/etc/pihole
      - /opt/docker_volume/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
networks:
  static_ip:
    external: true
