version: "2.1"

services:
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1006
      - PGID=1006
      - TZ=Asia/Shanghai
    volumes:
      - nextcloud_config:/config
      - nextcloud_data:/data
    networks:
      HomeNetwork:
        ipv4_address: 172.28.28.34
    restart: always
 
volumes:
  nextcloud_data:
    external: true
    
networks:
  HomeNetwork:
    external: true
