version: "2.1"
services:
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    volumes:
      - /opt/docker_volume/nextcloud_config:/config
      - /path/to/data:/data
    ports:
      - 443:443
    restart: unless-stopped
