
version: "2.3"
services:
  tmm:
    image: romancin/tinymediamanager:latest-v4
    container_name: tmm
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      - GROUP_ID=0
      - USER_ID=0
      - TZ=Asia/Shanghai
      - ENABLE_CJK_FONT=1
      - CLEAN_TMP_DIR=1
    ports:
      - 5800:5800
      - 5900:5900
    volumes:
      - /opt/docker_volume/tmm_config:/config
      - /mnt/cifs/media:/media
