version: "2.1"
services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    stdin_open: true
    tty: true
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - JELLYFIN_PublishedServerUrl=172.28.28.80
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /root/docker_volume/nfs/jellyfin_config:/config
      - /root/docker_volume/cifs/media:/data
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
    restart: always
