version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    stdin_open: true
    tty: true
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    volumes:
      - /mnt/nfs/docker_volume/mysql/db:/var/lib/mysql
      - /mnt/nfs/docker_volume/mysql/conf:/etc/mysql/conf.d
