version: "2.1"
services:
  unifi-controller:
    image: ghcr.io/linuxserver/unifi-controller
    container_name: unifi
    stdin_open: true
    tty: true
    environment:
      - PUID=0
      - PGID=0
      - MEM_LIMIT=2048M
    volumes:
      - /opt/docker_volume/unifi_config:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
    restart: unless-stopped
