version: "2.1"
services:
  homebridge:
    image: oznu/homebridge
    container_name: homebridge
    networks:
      HomeNetwork:
        ipv4_address: 172.28.28.33
    volumes: 
      - homebridge_config:/homebridge
    restart: unless-stopped

networks:
  HomeNetwork:
    external: true
    
volumes:
  homebridge_config:
    external: true
