services:
  homebridge:
    image: oznu/homebridge
    container_name: homebridge
    stdin_open: true
    tty: true
    environment:
      - PUID=0
      - PGID=0
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
      - TZ=Asia/Shanghai
    network_mode: host
    volumes: 
      - /opt/docker_volume/homebridge_config:/homebridge
    restart: always
