version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    volumes:
      - /opt/docker_volume/nginx-relay/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 32999:443
